import type { Metadata } from "next";
import BusmeSidebar from "../components/BusmeSidebar";

export const metadata: Metadata = {
    title: "BusMe - Administración superior",
    description: "Generated by create next app",
};

export default function SuperAdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const userRole = 'superadmin';

    return (
        <html lang="en">
            <body className="font-poppins">
                <div className="flex h-screen w-full bg-muted-100">
                    <BusmeSidebar userRole={userRole} />
                    {children}
                </div>
            </body>
        </html>
    );
}
