import type {Metadata} from "next";
import {Inter} from "next/font/google";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "BusMe - Administración superior",
    description: "Generated by create next app",
};

export default function SuperAdminLayout({
                                   children,
                               }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="font-poppins">
            <div className="flex h-screen bg-complementary-100 w-full">
                <div className="w-1/5 bg-white h-full">

                </div>
                {children}
            </div>
            </body>
        </html>
    );
}
